#Python Program


In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5],np.int64)

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
a.ndim

1

In [5]:
print(a[1:4])

[2 3 4]


In [6]:
a.shape

(5,)

In [7]:
a.size

5

In [8]:
a.dtype

dtype('int64')


**Array Creation**



In [9]:
b= np.array([[1,2,3],[4,5,6],[7,8,9,]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**numpy array creation objects**

In [11]:
zero=np.zeros((3,5))

In [12]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
range=np.arange(10)

In [14]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
linearspace=np.linspace(1,11,20)

In [16]:
linearspace

array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
        3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
        6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
        8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ])

In [17]:
empty=np.empty((3,3))

In [18]:
empty

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 1.937e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [19]:
emptylike=np.empty_like(range)

In [20]:
emptylike

array([    0,     1,     0,   548,  1212,     0,   768, 32763,   100,
           0])

In [21]:
identity=np.identity(5)

In [22]:
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr=arr.ravel()
arr.size

25

In [25]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a1=np.arange(12).reshape(4,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
# multiply
m=a@a1   
m

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [28]:
%timeit m = a @ a1


2.91 μs ± 218 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
