                #ITERATION OF ARRAY

In [1]:
import numpy as np      #1d

In [2]:
arr=np.array([5,10,15,20,25,30])
arr

array([ 5, 10, 15, 20, 25, 30])

In [6]:
for a in arr:
    print(a)

5
10
15
20
25
30


In [8]:
print(type(arr))
print(type(arr.dtype))
print(arr.ndim)

<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int32DType'>
1


In [10]:
import numpy as np      #2d

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [15]:
print(type(arr))
print(type(arr.dtype))
print(arr.ndim)

<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int32DType'>
2


In [ ]:
import numpy as np      #3d

In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,10,11]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 9, 10, 11]]])

In [18]:
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [ 9 10 11]]
