                                    #METHOD 1

In [35]:
import numpy as np

In [2]:
ar1=np.array([1,2,3])
ar2=np.array([4,5])
print(ar1)
print(ar2)

[1 2 3]
[4 5]


In [3]:
final=np.concatenate((ar1,ar2))
print(final)

[1 2 3 4 5]


                                   #METHOD 2

In [4]:
import numpy as np

In [24]:
ar1=np.array([1,2,3])
ar2=np.array([4,5])
print(ar1)
print(ar2)

[1 2 3]
[4 5]


In [25]:
final=np.hstack((ar1,ar2))
print(final)     #joing alog rows(horiz.)

[1 2 3 4 5]


In [38]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print(ar1)
print(ar2)


[1 2 3]
[4 5 6]


In [44]:
final=np.stack((ar1,ar2),axis=1)     #by default axis=0;
print(final)                         #that will print [[1 2 3] [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [36]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print(ar1)
print(ar2)

[1 2 3]
[4 5 6]


In [37]:
final=np.vstack((ar1,ar2))
print(final)            #joing alog column(vertical)

[[1 2 3]
 [4 5 6]]


In [39]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print(ar1)
print(ar2)

[1 2 3]
[4 5 6]


In [40]:
final=np.dstack((ar1,ar2))
print(final)    #joining along height(depth)

[[[1 4]
  [2 5]
  [3 6]]]


In [41]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print(ar1)
print(ar2)

[1 2 3]
[4 5 6]


In [42]:
final=np.column_stack((ar1,ar2))
print(final)  

[[1 4]
 [2 5]
 [3 6]]
