                                        #SEARCHING

In [1]:
import numpy as np

In [6]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [8]:
result=np.where(arr==30)
print(result)

(array([2], dtype=int64),)


                                            #SORTING

In [11]:
import numpy as np

In [12]:
arr=np.array([5,10,61,12,2,10])
arr

array([ 5, 10, 61, 12,  2, 10])

In [13]:
result=np.sort(arr)
result

array([ 2,  5, 10, 10, 12, 61])


string


In [16]:
arr=np.array(["disha","surya","aman","tanya","gaurav","sahil"])
arr

array(['disha', 'surya', 'aman', 'tanya', 'gaurav', 'sahil'], dtype='<U6')

In [17]:
result=np.sort(arr)
result

array(['aman', 'disha', 'gaurav', 'sahil', 'surya', 'tanya'], dtype='<U6')