                                        #SPLITING A 1D ARRAY

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [8]:
result=np.array_split(arr,2)      #2 for spliting into two arrays 
print(result)

[array([1, 2, 3]), array([4, 5, 6])]


In [9]:
print(result[0])
print(result[1])

[1 2 3]
[4 5 6]


                                         #SPLITING A 2D ARRAY

In [10]:
import numpy as np

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
result=np.array_split(arr,3)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]
